services:
  fastapi:
    # 개발 시 소스코드 즉시 반영
    volumes:
      - ./apps/adk/:/app:cached
    # 개발용 환경변수(필요시)
    # environment:
    # debugpy 포트 오픈
    ports:
      - "5678:5678"
    
    # Non DevContainer
    # command: >
    #   uv sync --group dev &&
    #   python -m debugpy --listen 0.0.0.0:5678 --wait-for-client
    #   -m uvicorn apps.presentation.api:app --host 0.0.0.0 --port 8000 --reload