"""Create Agent Table

Revision ID: a8e073b8d637
Revises: 45a7b6ac44e1
Create Date: 2025-12-30 15:34:32.123144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8e073b8d637'
down_revision: Union[str, Sequence[str], None] = '45a7b6ac44e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=256), nullable=False),
    sa.Column('tools', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='adk'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agents', schema='adk')
    # ### end Alembic commands ###
