"""empty message

Revision ID: 721cad43834c
Revises: 
Create Date: 2025-12-17 16:57:57.016175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from google.adk.sessions.database_session_service import DynamicJSON
from google.adk.sessions.database_session_service import DynamicPickleType
from google.adk.sessions.database_session_service import PreciseTimestamp

# revision identifiers, used by Alembic.
revision: str = '721cad43834c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_states',
    sa.Column('app_name', sa.String(length=128), nullable=False),
    sa.Column('state', DynamicJSON(), nullable=False),
    sa.Column('update_time', PreciseTimestamp(), nullable=False),
    sa.PrimaryKeyConstraint('app_name')
    )
    op.create_table('sessions',
    sa.Column('app_name', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('state', DynamicJSON(), nullable=False),
    sa.Column('create_time', PreciseTimestamp(), nullable=False),
    sa.Column('update_time', PreciseTimestamp(), nullable=False),
    sa.PrimaryKeyConstraint('app_name', 'user_id', 'id')
    )
    op.create_table('user_states',
    sa.Column('app_name', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('state', DynamicJSON(), nullable=False),
    sa.Column('update_time', PreciseTimestamp(), nullable=False),
    sa.PrimaryKeyConstraint('app_name', 'user_id')
    )
    op.create_table('events',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('app_name', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('invocation_id', sa.String(length=256), nullable=False),
    sa.Column('author', sa.String(length=256), nullable=False),
    sa.Column('actions', DynamicPickleType(), nullable=False),
    sa.Column('long_running_tool_ids_json', sa.Text(), nullable=True),
    sa.Column('branch', sa.String(length=256), nullable=True),
    sa.Column('timestamp', PreciseTimestamp(), nullable=False),
    sa.Column('content', DynamicJSON(), nullable=True),
    sa.Column('grounding_metadata', DynamicJSON(), nullable=True),
    sa.Column('custom_metadata', DynamicJSON(), nullable=True),
    sa.Column('usage_metadata', DynamicJSON(), nullable=True),
    sa.Column('citation_metadata', DynamicJSON(), nullable=True),
    sa.Column('partial', sa.Boolean(), nullable=True),
    sa.Column('turn_complete', sa.Boolean(), nullable=True),
    sa.Column('error_code', sa.String(length=256), nullable=True),
    sa.Column('error_message', sa.String(length=1024), nullable=True),
    sa.Column('interrupted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['app_name', 'user_id', 'session_id'], ['sessions.app_name', 'sessions.user_id', 'sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'app_name', 'user_id', 'session_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    op.drop_table('user_states')
    op.drop_table('sessions')
    op.drop_table('app_states')
    # ### end Alembic commands ###
